### ISSUE TITLE
Browser Extension Changes 20190909

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#12]
**Phase I** 

All Versions - both Our.News and FFI — both Chrome & Firefox

- [x] Remove the ad-blocker detection/warning message — it works, but seems to do more harm than good— most adblockers don’t have trouble with our extensions, but this blocks all ad blockers.

- [x] Change "Comment" to "Review" in the Triple-dot menu, and remove the "Feedback" link

- [x] If a not-logged-in user takes any action that requires a login, first display a popup message of some kind that says: "Welcome! Please login, or create a free account to take this action."  And has two button choices (1). Close — in which case the popup closes and the user is not redirected anywhere; and (2) Login/Register — which then opens the Login/register page as it does now.

- [ ] Add more tracking POSTs to track what users are doing:

1. post `loginneeded` if a not-logged-in user takes any action that requires a login
2. post `indicatorclick` if a user clicks on one of the indicators on the Fact Check card
3. post `indicatorclick` if a user clicks on the Allsides links on the Newstrition card

- [x] Add unique registration identifier (?CID) to the registration URL so we can track exactly what extension new users are signing up through. The CID code to pass is based on what version is being used. For example, if the current register URL is:  https://our.news/register, then the new one should be (based on the version used):

1.	For FFI Chrome — https://our.news/register/?CID=FFI.Chrome 
2.	For FFI Firefox — https://our.news/register/?CID=FFI.Firefox 
3.	For ON Chrome — https://our.news/register/?CID=ON.Chrome 
4.	For ON Firefox — https://our.news/register/?CID=On.Firefox 

- [x] Bump manifest version number and provide 

**Phase II**

Our.News versions only — both Chrome and Firefox

— Implement new “Nutrition Label” design, moving things around as shown on the attached mockup

![browser mockup](https://user-images.githubusercontent.com/35204816/64703428-66f5e380-d47a-11e9-9aed-9f26bd01e57a.png)

**Comment by rkzack** [comment]
@webcolor-in things look pretty good, thanks!  Just a couple issues:

- [ ]  The CID identifier was missing in a few places, but I added it-- nothing needed here

- [ ]  The `indicatorclick` post works except in one case:  on the Newstrition tab, if you click the Allsides Rating text-- ie. `Right` or `Left` --  it doesn't post.  It does post if you click the image, but not the actual text. It should post in both cases.

- [ ]  Could you please remove the AllSides line from the Fact-Check card

**Comment by webcolor-in** [comment]
Point 2 - Can you please share screenshot of link that is missed? I could see several links and inner images in them and haven't worked on this feature so have less know how.

Point 3 - This is dynamic text & link that is created based on info that comes from backend json.

**Comment by rkzack** [comment]
2-- attached

<img width="378" alt="2019-09-15_1204" src="https://user-images.githubusercontent.com/35204816/64924326-3a5f0600-d7b1-11e9-822c-796c740ee912.png">

3-- ok, never mind

**Comment by webcolor-in** [comment]
Fixed and code pushed to remote
